### ISSUE TITLE
Playback speeds only appearing on some pages and browsers

### ISSUE THREAD

**Issue by KieranM55** [CODESIGN2/media-playback-speed#14] opened 2023-02-07 08:51 UTC
Website for my guitar students to practice, and the speed buttons are only appearing on about 60% of our pages on my phone (Google Pixel 5 Android Version 13 - the same result on Chrome/Firefox), but they seem to appear on just about every page on Chrome on my Laptop (HP Omen Windows 10 - Chrome), but I do often get requests that my students can't see the buttons on their PC's as well. Phone/Tablet is the most common use from my students where they can't see the speed buttons.

Long time user and lover of your plugin, you've helped me before (hugely appreciated) and I'm sorry to bug you again, but I'm a very basic user so I hope the below info is enough for you.

**The Context**

* WordPress Version - Just updated to 6.1.1
* Other plugins - Advanced editor tools, Black studio tiny widget, Auto Install free SSL (premium), duplicate page, page builder by Site Origin, really simple SSL, Site Origina widgets bundle, Ultimate member, Updraft plus (backup/restore), WP Fastest Cache (currently deactived), WP Rollback
* Theme - Ample
* https://www.essendonguitarpractice.com.au/ - you mentioned not to include username or password - but this is for what a student will see, not my login to edit the site: TestUser // TestUser

**To Reproduce**

1. Ideally on a mobile phone on Chrome browser, login with the above
2. Go to the page 'Intermediate 2' and scroll down to see any of the audio players and see if the speed buttons appear.
3. If the speed buttons appear - please try other pages using the menu at the top to test
4. If they don't - go to the 'Beginner 1' page - and they should appear there (they do for me).

**Expected behavior**

The buttons have not appeared for me on Intermediate 2 for the last few months (we've been on holidays so I haven't contacted you), and inconsistently appear on Intermediate 1 and fingerpicking pages as well.

**Screenshots**

![Screenshot_20230207-185617](https://user-images.githubusercontent.com/71917711/217185445-c6089247-ce7f-4636-95b0-9955643e1fe6.jpg)
![Screenshot_20230207-185627](https://user-images.githubusercontent.com/71917711/217185475-d1390a01-fa56-43bb-ac77-17eb4488b161.jpg)

**Files**
 
[Intermediate 2 Webpage.zip](https://github.com/CODESIGN2/media-playback-speed/files/10673083/Intermediate.2.Webpage.zip)

</details>

**Additional context**

Again apologies for bugging you - it's a difficult problem to isolate as my students have various devices and browsers - but it seems that the same pages have the problem of the buttons not appearing - particularly Intermediate 2, and often Intermediate 1 (a lot of the levels are broken up into 2 actual pages because of a large amount of content on each one).

I've tried updating other plugins one at a time, and disabling them one at a time and it never seems to make a difference - I can't understand what I've done differently on different pages - except for initiailly using the 'duplicate page' plugin to create the 2nd half of each level on a separate page - but some of these have resulted in the buttons working fine, and some not.

I also just saw your other post about keeping this plugin alive - I can't find out how to have a speed button change on the default audio player in Wordpress? If this problem is too much work or you can't see the issue - would you have a link to an instructional page on adding the speed buttons using the default player? I only need it for audio - not video.

Thanks so much for your help - again this is such a massive important part of my site, so I appreciate any help at all!

Kieran

**Comment by Lewiscowles1986** [comment] 2023-02-07 22:58
Hey @KieranM55

https://github.com/CODESIGN2/media-playback-speed/issues/11 covers adding html buttons, it includes copy-paste HTML buttons, which you are free to style yourself using custom theme CSS or theme editing. 

If the players themselves load via JS, that could be the issue, which could be a part of a theme, or block plugin framework. This feels like a duplicate of #11 , or at least related.

**Closed as not planned** 2023-02-07 22:59 UTC
Labels: bug, duplicate
